version: '3'
services:
  mongodb:
    image: mongo:4.2.15
    container_name: mongo-pwndoc
    command: --wiredTigerCacheSizeGB 1 # 50% of (max RAM - 1GB) - minimum 0.25 (Modify it depending on defined RAM limits)
    deploy:
      resources:
        limits:
          memory: 3G # Maximum memory to allocate (Modify it depending on host ressources - leave at least 1GB free for host)
        reservations:
          memory: 1G # Minimum memory required
    volumes:
      - ./backend/mongo-data:/data/db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_DB:pwndoc
    networks:
      - backend

  pwndoc-backend:
    build: ./backend
    image: yeln4ts/pwndoc:backend
    container_name: pwndoc-backend
    volumes:
      - ./backend/report-templates:/app/report-templates
      - ./backend/src/config:/app/src/config
      - ./backend/backup:/app/backup
    depends_on:
      - mongodb
    restart: always
    ports:
      - 4242:4242
    links:
      - mongodb
    networks: 
      - backend

  pwndoc-frontend:
    build: ./frontend
    image: yeln4ts/pwndoc:frontend
    container_name: pwndoc-frontend
    restart: always
    ports:
      - 8443:8443
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
      driver: bridge
