version: '3'
services:

  mongodb:
    image: mongo:4.2.15
    container_name: mongo-pwndoc-dev
    command: --wiredTigerCacheSizeGB 1 # 50% of (max RAM - 1GB) - minimum 0.25 (Modify it depending on defined RAM limits)
    deploy:
      resources:
        limits:
          memory: 3G # Maximum memory to allocate (Modify it depending on host ressources - leave at least 1GB free for host)
        reservations:
          memory: 1G # Minimum memory required
    volumes:
      - ./mongo-data-dev:/data/db
    restart: always
    ports:
      - 127.0.0.1:27017:27017
    environment:
      - MONGO_DB:pwndoc
    networks:
      - backend

  pwndoc-backend:
    build: 
      context: .
      dockerfile:  Dockerfile.dev
    image: yeln4ts/pwndoc:backend-dev
    container_name: pwndoc-backend-dev
    volumes:
      - ./src:/app/src
      - ./ssl:/app/ssl
      - ./report-templates:/app/report-templates
      - ./backup:/app/backup
    depends_on:
      - mongodb
    restart: always
    ports:
      - 5252:5252
    links:
      - mongodb
    networks: 
      - backend

volumes:
  mongo-data-dev:

networks:
  backend:
    driver: bridge